hydra:
  output_subdir: null
  run:
    dir: /dev/null

cmd: ['prep'] #  ['prep', 'train', 'test', 'eval', 'plot', 'agg', 'fair']
data:
  domain:
    #cmn.publication.Publication
    #cmn.movie.Movie
    #cmn.repository.Repository
    cmn.patent.Patent
  source:
    #../data/dblp/toy.dblp.v12.json
    #../data/imdb/toy.title.basics.tsv
    #../data/gith/toy.data.csv
    ../data/uspt/toy.patent.tsv
  output:
    #../output/dblp/toy.dblp.v12.json
    #../output/imdb/toy.title.basics.tsv
    #../output/gith/toy.data.csv
    ../output/uspt/toy.patent.tsv

  filter:
    min_nteam: 10 # as this may yield empty teams, min_team_size should be set to at least 1
    min_team_size: 2 #no filter -> no key 'filter' or 'filter': {} or 'filter': {'min_nteam': 0, 'min_team_size': 0}
  location: 'venue' #should be one of 'city', 'state', 'country', represents the location of team members, or 'venue' represents the location of team like in dblp
  acceleration: 'cpu' #cpu for all cores, cpu:3 for 3 cores, 'cuda' for all gpus, 'cuda:1,3' for gpu1 and gpu3
  bucket_size: 1000

model:
    baseline:
        random:
            b: 128

train:
  nfolds: 3
  train_test_split: 0.85
  step_ahead: 2 #for now, it means that whatever are in the last [step_ahead] time interval will be the test set!