name: inclusive-tests-toys-main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-configs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json ~data.filter ~data.embedding"
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json data.filter.min_nteam=1 data.filter.min_team_size=2 ~data.embedding"
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json ~data.filter data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=../output/dblp/toy.dblp.v12.json/skill.d9.w10.dm1.e100.d2v"
          - "cmd=prep data.domain=cmn.publication.Publication data.source=../data/dblp/toy.dblp.v12.json data.output=../output/dblp/toy.dblp.v12.json data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null \"+data.embedding.model.gnn.graph.structure=[[[skill, to, team], [member, to, team], [loc, to, team]], stml]\""

          - "cmd=prep data.domain=cmn.movie.Movie data.source=../data/imdb/toy.title.basics.tsv data.output=../output/imdb/toy.title.basics.tsv ~data.filter ~data.embedding"
          - "cmd=prep data.domain=cmn.movie.Movie data.source=../data/imdb/toy.title.basics.tsv data.output=../output/imdb/toy.title.basics.tsv data.filter.min_nteam=1 data.filter.min_team_size=2 ~data.embedding"
          - "cmd=prep data.domain=cmn.movie.Movie data.source=../data/imdb/toy.title.basics.tsv data.output=../output/imdb/toy.title.basics.tsv ~data.filter data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.movie.Movie data.source=../data/imdb/toy.title.basics.tsv data.output=../output/imdb/toy.title.basics.tsv data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.movie.Movie data.source=../data/imdb/toy.title.basics.tsv data.output=../output/imdb/toy.title.basics.tsv ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.movie.Movie data.source=../data/imdb/toy.title.basics.tsv data.output=../output/imdb/toy.title.basics.tsv data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.movie.Movie data.source=../data/imdb/toy.title.basics.tsv data.output=../output/imdb/toy.title.basics.tsv ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=../output/imdb/toy.title.basics.tsv/skill.d9.w10.dm1.e100.d2v"

          - "cmd=prep data.domain=cmn.repository.Repository data.source=../data/gith/toy.repos.csv data.output=../output/gith/toy.repos.csv ~data.filter ~data.embedding"
          - "cmd=prep data.domain=cmn.repository.Repository data.source=../data/gith/toy.repos.csv data.output=../output/gith/toy.repos.csv data.filter.min_nteam=1 data.filter.min_team_size=2 ~data.embedding"
          - "cmd=prep data.domain=cmn.repository.Repository data.source=../data/gith/toy.repos.csv data.output=../output/gith/toy.repos.csv ~data.filter data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.repository.Repository data.source=../data/gith/toy.repos.csv data.output=../output/gith/toy.repos.csv data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.repository.Repository data.source=../data/gith/toy.repos.csv data.output=../output/gith/toy.repos.csv ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.repository.Repository data.source=../data/gith/toy.repos.csv data.output=../output/gith/toy.repos.csv data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.repository.Repository data.source=../data/gith/toy.repos.csv data.output=../output/gith/toy.repos.csv ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=../output/gith/toy.repos.csv/skill.d9.w10.dm1.e100.d2v"

          - "cmd=prep data.domain=cmn.patent.Patent data.source=../data/uspt/toy.patent.tsv data.output=../output/uspt/toy.patent.tsv ~data.filter ~data.embedding"
          - "cmd=prep data.domain=cmn.patent.Patent data.source=../data/uspt/toy.patent.tsv data.output=../output/uspt/toy.patent.tsv data.filter.min_nteam=1 data.filter.min_team_size=2 ~data.embedding"
          - "cmd=prep data.domain=cmn.patent.Patent data.source=../data/uspt/toy.patent.tsv data.output=../output/uspt/toy.patent.tsv ~data.filter data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.patent.Patent data.source=../data/uspt/toy.patent.tsv data.output=../output/uspt/toy.patent.tsv data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.d2v.D2v_d2v"
          - "cmd=prep data.domain=cmn.patent.Patent data.source=../data/uspt/toy.patent.tsv data.output=../output/uspt/toy.patent.tsv ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.patent.Patent data.source=../data/uspt/toy.patent.tsv data.output=../output/uspt/toy.patent.tsv data.filter.min_nteam=1 data.filter.min_team_size=2 data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=null"
          - "cmd=prep data.domain=cmn.patent.Patent data.source=../data/uspt/toy.patent.tsv data.output=../output/uspt/toy.patent.tsv ~data.filter data.embedding.class_method=mdl.emb.gnn.Gnn_n2v +data.embedding.model.gnn.graph.pre=../output/uspt/toy.patent.tsv/skill.d9.w10.dm1.e100.d2v"

      # Set to false if you want parallel runs:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Clean up previous outputs
        run: rm -rf output/

      - name: Run config ${{ matrix.config }}
        run: |
          python main.py ${{ matrix.config }} 
        working-directory: ./src
